vscode:
  extensions:
    - syler.sass-indented@1.6.9:GMvc45BKUu/SSSIDAxlZ7A==
image: gitpod/workspace-full
# Command to start on workspace startup (optional)
tasks:
  - init: npm install
    command: npm start
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000
    onOpen: open-preview